### ISSUE TITLE
kickoff tasks

### ISSUE THREAD

**Issue by fadc80** [fadc80/ionic-5-stars-worker#1]
Initially, lets complete these tasks:

- [x] Define product purpose
- [x] Define its major features
- [x] Create a prototype

Mark the task already done!

**Comment by andreporto** [comment]
Major features proposal:
- list workers by category
- add new worker
- edit worker
- worker detail
- add comment to a worker and set stars to it

**Comment by andreporto** [comment]
A just scatched a low fidelity prototype example at https://bit.ly/3fFmqCT

**Comment by fadc80** [comment]
The MVP 1 implementation was removed since it is going to be broken down into more specialized tasks.
